name: Just pushing
on:
  push:
    branches:
      - feature/PM-7674
      

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug
        run: |
          echo "event name is:" ${{ github.event_name }}
          echo "Pushed by ${{ github.actor }} to ${{ github.ref }}"


